FROM golang:alpine as build

WORKDIR /app
ADD . .
RUN export GOOS=linux
RUN export GOARCH=amd64
RUN export CGO_ENABLED=0
RUN export GO111MODULE=on

RUN go build

FROM alpine
RUN apk add --no-cache ca-certificates

COPY --from=build /app/drone-webhook /bin/
ENTRYPOINT ["/bin/drone-webhook"]
